spring:
  application:
    name: manage
  datasource:
    url: jdbc:mysql://localhost:3306/xxzx_oa
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # 对于MySQL 8.x, 使用 org.hibernate.dialect.MySQL8Dialect
        format_sql: true
# application.yml
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
